module.exports = {
 en: {
    wrongLogin: "Wrong Email or password",
    authKeyRequired: "authorization_key key is required",
    invaildAuth: "Invaild Authorization",
    signup: "User signup successfully",
    fieldRequired: "field is required",
    fieldsRequired: "fields are required",
    phoneRegister: "The Phone No is already registered. Kindly use another",
    emailRegister: "The Email is already registered. Kindly use another",
    verifyOtp: "Otp verify Successfully",
    invaildOtp: "Invaild Otp",
    otpSend:"Link send on your register email",
    mailNotFound: "Email not found",
    LoginMessage: "User Login Successfully",
    appInfo: "App Informations",
    oldPassword: "Old password is wrong",
    passwordchange: "Password change successfully",
    logoutUser: "User Logout successfully",
    profileUpdate: "Profile Updated Successfully",
    userProfile: "User Profile",
    postCreated: "Post add successfully",
    wrongPost: "Invaild Post",
    deletePost: "Post deleted sucdessfully",
    postLike: "Post Like Successfully",
    postDiLike: "Post dislike Successfully",
    commentAdd: "comment successfully",
    sharePost: "Post share successfully",
    deleteComment: "Comment Deleted Successfully",
    commentList: "Comment list",
    getPost: "Post listing",
    postUnfav: "Post unfavourite",
    postFav: "Post favourite successfully",
    needLogin: "Login first to access friend Post",
    getFavPost: "favourite listing",
    userNotFound: "user not found",
    requestSend: "request send successfully",
    requestCancel: "Request cancel",
    wrongRequest: "Wrong Request id",
    unFriend: "unfriend Successfully",
    cancelRequest: "Request Cancel successfully",
    acceptRequest: "Request Accepted",
    friendList:"Friend list",
    requestList: "Request List",
    userUnfav:"User un favourite successfully",
    userFav:"User favourite successfully",
    allPics:"Users all picture",
    categoryNotFound: "Category Not found",
    addJob:"Job added successfully",
    jobUnfav:"Job un favourite successfully",
    jobfav:"Job favourite successfully",
    getJobs:"Job listing",
    categoryList:"Category List",
    deleteJob:"deleted successfully",
    messageSend:"Message send successfully",
    messages:"Messages",
    lastChat:"last chats",
    threadInvaild: "Invaild Thread id",
    chatDelete:"Chat Deleted Successfully",
    userList:"users Listing",
    businessListing: "Business listing",
    NotificationListing: "Notification listing",
    bussinessCatgeory:"Catgegory Listing",
    OTP:"is your one time password to verify account on ROU.It is vaild for 30 minutes.Do not share your OTP with anyone"
 },
 es:{
    wrongLogin: "Correo o contraseña equivocada",
    authKeyRequired: "Se requiere clave de clave de autorización",
    invaildAuth: "Autorización de invasión",
    signup: "Registro de usuario exitoso",
    fieldRequired: "Se requiere campo",
    fieldsRequired: "Se requiere campo",
    phoneRegister: "El número de teléfono ya está registrado. Por favor use otro",
    emailRegister: "El correo electrónico ya está registrado. Por favor use otro",
    verifyOtp: "Otp verifica con éxito",
    invaildOtp: "Otp inválido",
    otpSend:"Otp envíe su correo electrónico de registro",
    mailNotFound: "El correo electrónico no encontrado",
    LoginMessage: "Inicio de sesión de usuario con éxito",
    appInfo: "Información de la aplicación",
    oldPassword: "La contraseña anterior es incorrecta",
    passwordchange: "Cambio de contraseña exitosamente",
    logoutUser: "Cierre de sesión de usuario correctamente",
    profileUpdate: "Perfil actualizado con éxito",
    userProfile: "Perfil del usuario",
    postCreated: "Publicar agregar correctamente",
    wrongPost: "Publicación inválida",
    deletePost: "Publicación eliminada con éxito",
    postLike: "Publicar Me gusta con éxito",
    postDiLike: "Publicar no me gusta con éxito",
    commentAdd: "comenta con éxito",
    sharePost: "Publicar compartir correctamente",
    deleteComment: "Comentario eliminado con éxito",
    commentList: "Lista de comentarios",
    getPost: "Listado de publicaciones",
    postUnfav: "Publicar en favoritos",
    postFav: "Publicar favorito con éxito",
    needLogin: "Inicie sesión primero para acceder a la publicación de un amigo",
    getFavPost: "listado favorito",
    userNotFound: "usuario no encontrado",
    requestSend: "solicitud enviar con éxito",
    requestCancel: "Solicitud cancelar",
    wrongRequest: "ID de solicitud incorrecta",
    unFriend: "no amigo con éxito",
    cancelRequest: "Solicitar cancelar con éxito",
    acceptRequest: "Petición aceptada",
    friendList:"Lista de amigos",
    requestList: "Lista de solicitudes",
    userUnfav:"Usuario un favorito con éxito",
    userFav:"Favorito del usuario con éxito",
    allPics:"Usuarios todos foto",
    categoryNotFound: "Categoría no encontrada",
    addJob:"Trabajo agregado exitosamente",
    jobUnfav:"Job un favorito con éxito",
    jobfav:"Trabajo favorito con éxito",
    getJobs:"Listado de trabajo",
    categoryList:"Lista de categoría",
    deleteJob:"borrado exitosamente",
    messageSend:"Mensaje enviado exitosamente",
    messages:"Messages",
    lastChat:"últimos chats",
    threadInvaild: "Id. De hilo de invasión",
    chatDelete:"Chat eliminado exitosamente",
    userList:"Listado de usuarios",
    businessListing: "Listado de negocios",
    NotificationListing: "Listado de notificaciones",
    bussinessCatgeory:"Listado de categoría comercial",
    OTP:"es su contraseña de un solo uso para verificar la cuenta en ROU. Es valiosa durante 30 minutos. No comparta su OTP con nadie",
   }, ro: {
    wrongLogin: "Email sau parolă gresită",
    authKeyRequired: "cheie_autorizare cheia este necesar",
    invaildAuth: "Autorizare invalidă",
    signup: "Înscriere utilizator reușită",
    fieldRequired: "Câmpul este necesar",
    fieldsRequired: "Câmpurile sunt necesare",
    phoneRegister: "Numărul de telefon este deja înregistrat. Te rugăm să folosești altul",
    emailRegister: "Adresa de email este deja înregistrată. Te rugăm să folosești alta",
    verifyOtp: "Parolă unică verificată cu succes",
    invaildOtp: "Parolă unică invalidă",
    otpSend: " Link-ul a fost trimis pe adresa de email înregistrat",
    mailNotFound: "Email-ul nu a fost găsit",
    LoginMessage: "Autentificare utilizator reușită",
    appInfo: "Informații aplicație",
    oldPassword: "Parola veche este greșită",
    passwordchange: "Parola a fost schimbată cu succes",
    logoutUser: "Delogare utilizator reușită",
    profileUpdate: "Profilul a fost updatat cu succes",
    userProfile: "Profilul utilizatorului",
    postCreated: "Anunț postat cu succes",
    wrongPost: "Postare invalidă",
    deletePost: "Postare ștearsă cu success",
    postLike: "Postare like reușită",
    postDiLike: " Postare dislike reușită",
    commentAdd: "Adăugare comentariu reușită",
    sharePost: "Postare distribuită cu succes",
    deleteComment: "Comentariu șters cu succes",
    commentList: "Listă comentarii",
    getPost: "Postează listare",
    postUnfav: "Postează nefavorite",
    postFav: "Postare favorite cu succes",
    needLogin: "Loghează-te înainte pentru a accesa postarea prietenului",
    getFavPost: "Listă favorite",
    userNotFound: "Utilizator negăsit",
    requestSend: "Cerere trimisă cu succes",
    requestCancel: "Anulează cererea",
    wrongRequest: "Id cerere gresit",
    unFriend: "Scoatere prieten cu succes",
    cancelRequest: "Anulare cerere cu succes",
    acceptRequest: "Cerere acceptată",
    friendList:"Listă prieteni",
    requestList: "Listă cereri",
    userUnfav:"Utilizator scos de la favoriți cu succes",
    userFav:"Utilizator adăugat la favoriți cu succes",
    allPics:"Toate pozele utilizatorului",
    categoryNotFound: "Categorie negăsită",
    addJob:"Job adăugat cu succes",
    jobUnfav:"Job scos de la favorite cu succes",
    jobfav:"Job adăugat la favorite cu succes",
    getJobs:"Listă joburi",
    categoryList:"Listă categorii",
    deleteJob:"Șters cu succes",
    messageSend:"Mesaj trimis cu succes",
    messages:"Mesaje",
    lastChat:"Ultimele conversații",
    threadInvaild: "Id subiect invalid",
    chatDelete:"Conversație ștearsă cu succes",
    userList:"Listă utilizatori",
    businessListing: "Listă afaceri",
    NotificationListing: "Listă notificări",
    bussinessCatgeory:"Listă categorii de afaceri",
    OTP:"este o parolă unică folosită pentru a verifica un cont pe ROU. Este validă pentru 30 de minute. Nu împărtăși OTP-ul tău cu nimeni",
 }
}